import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { AdminButton, AdminInput, AdminPageHeader } from "../components/AdminUi.jsx";
import { adminApi } from "../services/adminApi.js";

const reorder = (items, index, amount) => { const next = [...items]; const target = index + amount; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next; };
const newKey = () => `nav-${globalThis.crypto?.randomUUID?.() || Date.now()}`.toLowerCase();

export default function NavbarManagementPage() {
  const [config, setConfig] = useState({ items: [] }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { adminApi.navbar().then((data) => setConfig(data.navbar)).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const updateParent = (index, patch) => setConfig((current) => ({ items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const toggleParent = (index) => { const item = config.items[index]; if (item.active && item.children.some((child) => child.active) && !window.confirm(`Hide ${item.label} and all of its active dropdown items from the public navbar?`)) return; updateParent(index, { active: !item.active }); };
  const updateChild = (parentIndex, childIndex, patch) => updateParent(parentIndex, { children: config.items[parentIndex].children.map((child, index) => index === childIndex ? { ...child, ...patch } : child) });
  const save = async () => { setSaving(true); setError(""); setMessage(""); try { const data = await adminApi.saveNavbar(config); setConfig(data.navbar); setMessage("Navbar configuration saved. Public navigation will use these active items."); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  if (loading) return <p className="p-6 text-sm font-semibold">Loading navbar configuration…</p>;
  return <div><AdminPageHeader title="Navbar Management" description="Configure public navigation without changing or deleting products." action={<AdminButton loading={saving} onClick={save}>Save changes</AdminButton>} />
    {error && <p role="alert" className="mb-4 border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{message && <p role="status" className="mb-4 border border-green-200 bg-green-50 p-3 text-sm font-bold text-green-800">{message}</p>}
    <div className="grid gap-5">{config.items.map((item, parentIndex) => <section key={item.key} className="border border-ink/10 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto_auto]"><AdminInput label="Top-level label" value={item.label} onChange={(e) => updateParent(parentIndex, { label: e.target.value })} /><AdminInput label="Destination" value={item.href} onChange={(e) => updateParent(parentIndex, { href: e.target.value })} /><label className="flex items-center gap-2 self-end pb-2 text-sm font-bold"><input type="checkbox" checked={item.dropdownEnabled} onChange={(e) => updateParent(parentIndex, { dropdownEnabled: e.target.checked })} />Dropdown</label><button type="button" onClick={() => toggleParent(parentIndex)} className={`h-10 self-end px-4 text-sm font-bold ${item.active ? "bg-green-100 text-green-800" : "bg-ink/10 text-ink/55"}`}>{item.active ? "Active" : "Inactive"}</button></div>
      <div className="mt-4 flex gap-2"><AdminButton variant="secondary" disabled={parentIndex === 0} onClick={() => setConfig((current) => ({ items: reorder(current.items, parentIndex, -1) }))}><ArrowUp size={15} /></AdminButton><AdminButton variant="secondary" disabled={parentIndex === config.items.length - 1} onClick={() => setConfig((current) => ({ items: reorder(current.items, parentIndex, 1) }))}><ArrowDown size={15} /></AdminButton></div>
      {item.dropdownEnabled && <div className="mt-5 border-t border-ink/10 pt-4"><h2 className="font-bold">{item.label} dropdown</h2><div className="mt-3 grid gap-3">{item.children.map((child, childIndex) => <div key={child.key} className="grid gap-2 bg-linen/50 p-3 md:grid-cols-[1fr_1.5fr_auto_auto]"><AdminInput label="Display name" value={child.label} onChange={(e) => updateChild(parentIndex, childIndex, { label: e.target.value })} /><AdminInput label="Destination" value={child.href} onChange={(e) => updateChild(parentIndex, childIndex, { href: e.target.value })} /><button type="button" onClick={() => updateChild(parentIndex, childIndex, { active: !child.active })} className={`h-10 self-end px-3 text-sm font-bold ${child.active ? "bg-green-100 text-green-800" : "bg-ink/10 text-ink/55"}`}>{child.active ? "Active" : "Inactive"}</button><div className="flex items-end gap-1"><AdminButton variant="secondary" disabled={childIndex === 0} onClick={() => updateParent(parentIndex, { children: reorder(item.children, childIndex, -1) })}><ArrowUp size={14} /></AdminButton><AdminButton variant="secondary" disabled={childIndex === item.children.length - 1} onClick={() => updateParent(parentIndex, { children: reorder(item.children, childIndex, 1) })}><ArrowDown size={14} /></AdminButton><AdminButton variant="danger" onClick={() => updateParent(parentIndex, { children: item.children.filter((_, index) => index !== childIndex) })}><Trash2 size={14} /></AdminButton></div></div>)}</div>
        <AdminButton className="mt-3" variant="secondary" onClick={() => updateParent(parentIndex, { children: [...item.children, { key: newKey(), label: "New item", type: "LINK", href: "/shop", active: true, order: item.children.length + 1 }] })}><Plus size={15} />Add navigation item</AdminButton></div>}
    </section>)}</div></div>;
}
