import { Router } from "express";
import { createPaymentIntent, getOrderConfirmation, getPaymentStatus, verifyPayment } from "../controllers/paymentController.js";
import { protect } from "../middleware/auth.js";
import { validate } from "../middleware/validate.js";
import { checkoutConfirmationValidator, paymentIntentValidator, paymentStatusValidator, paymentVerifyValidator } from "../validators/paymentValidators.js";
const router = Router();
router.post("/intent", protect, paymentIntentValidator, validate, createPaymentIntent);
router.post("/verify", protect, paymentVerifyValidator, validate, verifyPayment);
router.get("/checkout/:checkoutSessionId/confirmation", protect, checkoutConfirmationValidator, validate, getOrderConfirmation);
router.get("/:cashfreeOrderId/status", protect, paymentStatusValidator, validate, getPaymentStatus);
export default router;
