// Centralizes API paths for backend communication.
export const API_BASE_URL = "/api";

export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    google: "/auth/google",
    otpRequest: "/auth/otp/request",
    otpVerify: "/auth/otp/verify",
    continueAdminLogin: "/auth/admin-login/continue",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    profile: "/auth/profile",
    changePassword: "/auth/change-password",
    requestOtp: "/auth/otp/security-code",
    security: "/auth/security",
    sessions: "/auth/sessions",
    session: (id) => `/auth/sessions/${id}`,
    addresses: "/auth/addresses",
    address: (id) => `/auth/addresses/${id}`,
  },
  products: "/products",
  featuredProducts: "/products/featured",
  product: (slug) => `/products/${slug}`,
  relatedProducts: (id, limit = 6) => `/products/${id}/related?limit=${limit}`,
  categories: "/categories",
  cart: "/cart",
  cartSync: "/cart/sync",
  cartItems: "/cart/items",
  cartItem: (id) => `/cart/items/${id}`,
  wishlist: "/wishlist",
  wishlistItem: (id) => `/wishlist/${id}`,
  orders: "/orders",
  shippingQuote: "/orders/shipping-quote",
  myOrders: "/orders/my",
  order: (id) => `/orders/${id}`,
  orderTracking: (id) => `/orders/${id}/tracking`,
  adminAdvanceMockShipment: (id) => `/admin/orders/${id}/mock-shipment/next`,
  paymentIntent: "/payments/intent",
  paymentVerify: "/payments/verify",
  contact: "/contact",
  offers: "/content/offers",
  couponValidate: "/content/coupons/validate",
  faqs: "/content/faqs",
  gallery: "/content/gallery",
  carousel: "/carousel",
  pageContent: (slug) => `/content/pages/${slug}`,
};


