import { Check, ChevronLeft, MessageCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";
import Button from "../components/ui/Button.jsx";
import Container from "../components/ui/Container.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { requestOtp, verifyOtp } from "../services/authService.js";

export default function VerifyOtp() {
  const location = useLocation(), navigate = useNavigate(), { refreshAuth } = useAuth(), firstRef = useRef(null);
  const flow = location.state;
  const [digits, setDigits] = useState(["", "", "", "", "", ""]), [loading, setLoading] = useState(false), [error, setError] = useState(""), [seconds, setSeconds] = useState(60), [success, setSuccess] = useState(false);
  useEffect(() => { if (seconds <= 0) return; const timer = setInterval(() => setSeconds((s) => s - 1), 1000); return () => clearInterval(timer); }, [seconds]);
  if (!flow?.phone || !flow?.purpose) return <Navigate to="/login" replace />;
  const code = digits.join("");
  function update(index, value) { const digit = value.replace(/\D/g, "").slice(-1); setDigits((current) => current.map((item, i) => i === index ? digit : item)); if (digit) document.querySelector(`[data-otp-index="${index + 1}"]`)?.focus(); }
  function keyDown(index, event) { if (event.key === "Backspace" && !digits[index]) document.querySelector(`[data-otp-index="${index - 1}"]`)?.focus(); }
  function paste(event) { const pasted = event.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6); if (pasted.length) { event.preventDefault(); setDigits(Array.from({ length: 6 }, (_, i) => pasted[i] || "")); } }
  async function verify(event) { event.preventDefault(); if (code.length !== 6) return setError("Enter the complete 6-digit code."); setLoading(true); setError(""); try { const data = await verifyOtp({ phone: flow.phone, purpose: flow.purpose, otp: code }); setSuccess(true); await refreshAuth(); setTimeout(() => navigate(flow.from || (data.user?.role === "admin" ? "/admin" : "/account"), { replace: true }), 650); } catch (err) { setError(err.message); setDigits(["", "", "", "", "", ""]); firstRef.current?.focus(); } finally { setLoading(false); } }
  async function resend() { if (seconds > 0 || loading) return; setLoading(true); setError(""); try { await requestOtp({ phone: flow.phone, purpose: flow.purpose, name: flow.name }); setSeconds(60); setDigits(["", "", "", "", "", ""]); } catch (err) { setError(err.message); const retry = err.errors?.[0]?.retryAfter; if (retry) setSeconds(retry); } finally { setLoading(false); } }
  return <section className="relative grid min-h-[100dvh] place-items-center bg-linen px-4 py-14"><button onClick={() => navigate(-1)} className="absolute left-4 top-4 inline-flex h-10 items-center gap-2 bg-white px-4 text-sm font-bold shadow-sm"><ChevronLeft size={17}/>Back</button><Container className="grid place-items-center"><form onSubmit={verify} className="w-full max-w-md border border-ink/10 bg-white p-6 shadow-soft sm:p-9">{success?<div role="status" className="py-12 text-center"><span className="mx-auto grid h-16 w-16 place-items-center bg-leaf text-white"><Check size={30}/></span><h1 className="mt-5 font-serif text-4xl font-semibold">You’re verified</h1><p className="mt-3 text-ink/60">Opening your account…</p></div>:<><div className="mb-7 flex h-12 w-12 items-center justify-center bg-leaf text-white"><MessageCircle size={22}/></div><p className="text-xs font-bold uppercase tracking-[0.22em] text-clay">Verify mobile number</p><h1 className="mt-3 font-serif text-5xl font-semibold">Check WhatsApp</h1><p className="mt-4 leading-7 text-ink/60">Enter the code sent to <strong className="text-ink">{flow.maskedPhone || "+91 ******"}</strong>. It expires in 5 minutes.</p><div className="mt-7 grid grid-cols-6 gap-2" onPaste={paste}>{digits.map((digit,index)=><input key={index} ref={index===0?firstRef:null} data-otp-index={index} value={digit} onChange={(e)=>update(index,e.target.value)} onKeyDown={(e)=>keyDown(index,e)} inputMode="numeric" autoComplete={index===0?"one-time-code":"off"} aria-label={`OTP digit ${index+1}`} className="h-14 min-w-0 border border-ink/15 text-center text-xl font-bold outline-none focus:border-leaf focus:ring-2 focus:ring-leaf/15" autoFocus={index===0}/>)}</div>{error&&<p role="alert" className="mt-5 bg-danger/5 p-4 text-sm font-semibold text-danger">{error}</p>}<Button type="submit" loading={loading} className="mt-7 w-full">Verify</Button><div className="mt-5 text-center text-sm text-ink/60">Didn&apos;t receive the code? <button type="button" disabled={seconds>0||loading} onClick={resend} className="font-bold text-leaf disabled:text-ink/35">{seconds>0?`Resend in ${seconds}s`:"Resend OTP"}</button></div></>}</form></Container></section>;
}
